"""empty message

Revision ID: 70382d5d831f
Revises: f99e9b80de4d
Create Date: 2023-07-18 11:55:47.318652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70382d5d831f'
down_revision = 'f99e9b80de4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
